# Movement Pattern Preview

## Introduction
This notebook is a tool to visualize how the movement patterns will look based on 
the currently supported movement function options. It covers the following shapes:
- square
- cross
- radial
- circle

The cells can be modified to view the effects of different argument values, but please 
note that any material changes to the code forming these patterns will not be 
reflected in the model itself without establishing a new movement function option.
If you do so, the developer encourages you to kindly share it in a pull request so that
others may potentially benefit from the new form. The reported complexity of forming each mask is based on N = 2*range_max + 1.

In [2]:
import torch

In [6]:
# "square" 
# Complexity: O(N^2)

range_max = 1
range_min = 1

possibility_mask = torch.ones(2 * range_max + 1, 2*range_max + 1)
possibility_mask[range_max - range_min + 1:range_max + range_min, 
                   range_max - range_min + 1:range_max + range_min] = 0
print(possibility_mask)



tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])


In [ ]:
# "circle"
# Complexity: O(N^2)
range_max = 3
range_min = 2

y, x = torch.meshgrid(torch.arange(range_max*2+1), torch.arange(range_max*2+1))
possibility_mask = torch.sqrt((x - range_max).float()**2 + (y - range_max).float()**2).round()
possibility_mask[possibility_mask>range_max] = 0
possibility_mask[possibility_mask<range_min] = 0
possibility_mask[possibility_mask>0] = 1
print(possibility_mask)


tensor([[0., 0., 1., 1., 1., 0., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [1., 1., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 1., 1.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 0., 1., 1., 1., 0., 0.]])


In [ ]:
# "radial"
# Complexity: O(N)
range_max = 3
range_min = 2

possibility_mask = torch.zeros(2*range_max+1, 2*range_max+1)
possibility_mask[range_max, :] = 1
possibility_mask[:, range_max] = 1
for i in range(2*range_max+1):
    possibility_mask[i, possibility_mask.size(1) - 1 - i] = 1
    possibility_mask[i, i] = 1
possibility_mask[range_max-range_min+1:range_max+range_min, range_max-range_min+1:range_max+range_min] = 0

print(possibility_mask)

tensor([[1., 0., 0., 1., 0., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 1., 0.],
        [1., 0., 0., 1., 0., 0., 1.]])


In [ ]:
#cross
# Complexity: O(N)
range_max = 3
range_min = 0

possibility_mask = torch.zeros(2*range_max+1, 2*range_max+1)
possibility_mask[range_max, :] = 1
possibility_mask[:, range_max] = 1
possibility_mask[range_max-range_min+1:range_max+range_min, range_max-range_min+1:range_max+range_min] = 0

print(possibility_mask)

tensor([[0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]])


In [13]:
# Edge Case Behavior
range_max = 1
range_min = 1

x_max = 2 * range_max + 1
y_max = 2 * range_max + 1

x = 0
y = 0

possibility_mask = torch.ones(2 * range_max + 1, 2 * range_max + 1)
possibility_mask[range_max - range_min + 1:range_max + range_min, 
                   range_max - range_min + 1:range_max + range_min] = 0
if (x - range_max >= 0 and y - range_max >= 0 and x + range_max <= x_max 
    and y + range_max < y_max):
    cropped_mask = possibility_mask

else:
    x_ll = max(0, range_max - x)
    x_ul = 2 * range_max + 1 - max(0, x + range_max - (2 * range_max + 1 - 1))
    y_ll = max(0, range_max - y)
    y_ul = 2 * range_max + 1 - max(0, y + range_max - (2 * range_max + 1 - 1))

    cropped_mask = possibility_mask[x_ll:x_ul, y_ll:y_ul]

'''

else:
    if x - range_max < 0:
        difference = range_max - x
        cropped_mask = possibility_mask[difference:, :]
    elif x + range_max > x_max:
        difference = x + range_max - x_max
        cropped_mask = possibility_mask[:-difference, :]
    elif y - range_max < 0:
        difference = range_max - y
        cropped_mask = possibility_mask[:, difference:]
    elif y + range_max > y_max:
        difference = y + range_max - y_max
        cropped_mask = possibility_mask[:, :-difference] 
'''
print(cropped_mask)



tensor([[0., 1.],
        [1., 1.]])
