In [1]:
import sys
sys.path.append('../dgl_ptm')
import dgl_ptm
import os
os.environ["DGLBACKEND"] = "pytorch"
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
model = dgl_ptm.PovertyTrapModel(model_identifier='misc_test')
seed=42


In [ ]:
model.set_model_parameters(**{'number_agents': 20, 
    'seed':seed,
    'sigma_dist': {'type':'uniform','parameters':[0.05,1.94],'round':True,'decimals':1},
    'a_theta_dist': {'type':'uniform','parameters':[0.1,1],'round':False,'decimals':None},
    'sensitivity_dist':{'type':'uniform','parameters':[0.0,1],'round':False,'decimals':None},
    'capital_dist': {'type':'uniform','parameters':[0.1,10.],'round':False,'decimals':None}, 
    'alpha_dist': {'type':'normal','parameters':[1.08,0.074],'round':False,'decimals':None},
    'lambda_dist': {'type':'uniform','parameters':[0.05,0.94],'round':True,'decimals':1},
    'spatial': True,
    'spatial_creation_args':{'method':"distribution",'x':3,'y':2,'properties':{'rand_value':{'type':'uniform','parameters':[0.1,1],'round':False,'decimals':None}}},
    'spatial_assignment_args':{'method':"property",'property':"rand_value"},
    'initial_graph_type': 'barabasi-albert',
    'initial_graph_args': {'seed': seed, 'new_node_edges':5},
    'device': 'cpu',
    'step_target':5,
    'steering_parameters':{'npath':'./agent_data.zarr',
                            'epath':'./edge_data', 
                            'ndata':[['degree','i_a','income','net_trade', 'tech_index','theta', 'wealth', 'wealth_consumption','weighted_degree'],['initial_only',['alpha','lambda','sigma','sensitivity']]],
                            'edata':None,
                            'mode':'w',
                            'capital_method':'past_shock',
                            'trade_method':'weighted_transfer',
                            'income_method':'income_generation',
                            'tech_gamma': torch.tensor([0.3,0.35,0.45]),
                            'tech_cost': torch.tensor([0,0.15,0.65]),
                            'consume_method':'past_shock_bellman_consumption',
                            'nn_path': "/nn_data/both_PudgeSixLayer_1024/0723_110813/model_best.pth",
                            'adapt_m':torch.tensor([0,0.5,0.9]),
                            'adapt_cost':torch.tensor([0,0.25,0.45]),
                            'depreciation': 0.08,
                            'discount': 0.95,
                            'global_theta_dist': None,
                            'global_theta': [1,1,1,0.7,1],
                            'del_method':'size',
                            'del_threshold':'balance',
                            'noise_ratio': 0.05,
                            'local_ratio': 0.25,
                            #'homophily_parameter': 1,
                            #'characteristic_distance': 3.33,
                            'homophily_basis':{'wealth':{'keys':["wealth"],'homophily_parameter':1,'characteristic_distance':3.33}},
                                               #,'position':{'keys':["x","y"],'homophily_parameter':2,'characteristic_distance':1}}, 
                            'truncation_weight':1.0e-10,
                            'step_type':'ptm'}})



{'edata': None, 'epath': './edge_data', 'format': 'xarray', 'mode': 'w', 'ndata': [['degree', 'i_a', 'income', 'net_trade', 'tech_index', 'theta', 'wealth', 'wealth_consumption', 'weighted_degree'], ['initial_only', ['alpha', 'lambda', 'sigma', 'sensitivity']]], 'npath': './agent_data.zarr', 'capital_method': 'past_shock', 'trade_method': 'weighted_transfer', 'income_method': 'income_generation', 'consume_method': 'past_shock_bellman_consumption', 'nn_path': '/nn_data/both_PudgeSixLayer_1024/0723_110813/model_best.pth', 'capital_update_method': 'default', 'characteristic_distance': 35, 'homophily_parameter': 0.69, 'homophily_basis': {'wealth': {'keys': ['wealth'], 'homophily_parameter': 1, 'characteristic_distance': 3.33}, 'position': {'keys': ['x', 'y'], 'homophily_parameter': 2, 'characteristic_distance': 1}}, 'adapt_m': tensor([0.0000, 0.5000, 0.9000]), 'adapt_cost': tensor([0.0000, 0.2500, 0.4500]), 'depreciation': 0.08, 'discount': 0.95, 'global_theta': [1.0, 1.0, 1.0, 0.7, 1.0], 

In [4]:
model.initialize_model()
print(model.config)
print(model.config.steering_parameters.global_theta)

Model torch seed set to 42
Using seed 42 for network creation with 5 edges requested.
tensor([[0.8940, 0.9235],
        [0.4446, 0.9634],
        [0.4514, 0.6408]])
tensor([0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
        1., 1.])
tensor([0., 1., 1., 2., 2., 0., 0., 0., 0., 2., 2., 0., 1., 0., 1., 1., 1., 0.,
        1., 0.])
20 agents initialized on cpu device
{'wealth': {'keys': ['wealth'], 'homophily_parameter': 1, 'characteristic_distance': 3.33}, 'position': {'keys': ['x', 'y'], 'homophily_parameter': 2, 'characteristic_distance': 1}}
tensor([0.3977, 0.4760, 0.0364, 0.0059, 0.0958, 0.0174, 0.4467, 0.4348, 0.4629,
        0.2977, 0.0227, 0.3433, 0.1129, 0.4398, 0.1819, 0.2692, 0.4670, 0.2923,
        0.4682, 0.0242, 0.4280, 0.4520, 0.4731, 0.4562, 0.4638, 0.1237, 0.1111,
        0.4721, 0.2502, 0.1146, 0.4513, 0.0018, 0.0022, 0.0218, 0.4047, 0.4329,
        0.2376, 0.0053, 0.0655, 0.0373, 0.0579, 0.2030, 0.0064, 0.3187, 0.3334,
        0.3945, 0.3486,

In [5]:
model.run()

#tensor([14,  6, 35, 22,  0, 21,  9, 62, 52,  2,  7, 12, 46,  8,  7, 12, 52, 67,
#        79, 52, 67, 21, 74, 67, 64])

performing step 0 of 5
Agent graph storage type: torch.int32
Income:tensor([2.5049, 1.9366, 2.0982, 1.3181, 0.6590])
scaled i_a: tensor([0.2500, 0.0000, 0.0000, 0.4500, 0.0000])
Setting 0 negative consumption predictions to zero,0 were less than -0.1 .
Based on alpha: tensor([1.2441, 1.1187, 1.1057, 1.0654, 1.1644])
Based on k: tensor([7.9075, 5.9357, 7.5638, 2.0329, 0.1500])
Based on sigma: tensor([0.9000, 0.4000, 0.3000, 0.4000, 0.7000])
Based on theta: tensor([0.8841, 0.2197, 0.4723, 0.6440, 0.7823])
Prediction [[0.2526611387729645, 0.17762678861618042], [0.00038809701800346375, 0.22065164148807526], [0.00042406097054481506, 0.3612349331378937], [0.44367632269859314, 0.055075399577617645], [0.00028576701879501343, 0.015261515974998474]]
Planned consumption tensor([0.1776, 0.2207, 0.3612, 0.0551, 0.0153])
Planned consumption percentage tensor([ 2.2463,  3.7174,  4.7759,  2.7091, 10.1775])
Planned i_a tensor([0.2500, 0.0000, 0.0000, 0.4500, 0.0000])
Agents in violation: 0
ATTENTION: N

In [6]:
tensor([0.7955, 0.9520, 0.0728, 0.0118, 0.1916, 0.0347, 0.8934, 0.8697, 0.9257,
tensor([7.0934e-01, 7.8208e-02, 9.2344e-01, 1.0051e-03, 6.8519e-02, 8.2070e-01,

SyntaxError: incomplete input (2916274588.py, line 2)

In [ ]:
import zarr
import os
zarr_file_one = zarr.open('/Users/victoria/Documents/Scripts/Python/DGL-PTM/Sensitivity_Analysis/data_mode_A/agent_data.zarr', mode='r')
zarr_file_two = zarr.open('/Users/victoria/Documents/Scripts/Python/DGL-PTM/Sensitivity_Analysis/data_mode_B/agent_data.zarr', mode='r')
zarr_file_three = zarr.open('/Users/victoria/Documents/Scripts/Python/DGL-PTM/Sensitivity_Analysis/data_mode_B/agent_data_initial.zarr', mode='r')
zarr_file_four = zarr.open('/Users/victoria/Documents/Scripts/Python/DGL-PTM/Sensitivity_Analysis/SA_test/agent_data.zarr', mode='r')

#print(zarr_file_one.tree())
#print(zarr_file_two.tree())
#print(zarr_file_three.tree())

#attributes=os.listdir('/Users/victoria/Documents/Scripts/Python/DGL-PTM/Sensitivity_Analysis/test_SA/agent_data.zarr')
#attributes = [item for item in attributes if item not in ['.zattrs','.zmetadata','.zgroup']]
#attributes = {key: None for key in attributes}
#print(attributes)
#print(zarr_file_one['wealth'][0:2])
#print(zarr_file_two['wealth'][0:2])

#print(zarr_file_one['alpha'][0:2])
#print(zarr_file_two['alpha'][0:2])

#format: zarr_file['property'][agent(s),timestep(s)]
print(zarr_file_four['wealth'][0:20,0])

#Unnecessary:'a_table','m','tec','gamma','cost','zeros','ones', 'total_weight', "disposable_wealth"
#One-Time: 'alpha',"lambda","sigma","sensitivity"
#Every-Time: 'degree','i_a','income','net_trade', 'tech_index','theta', 'wealth', 'wealth_consumption','weighted_degree'


[8.834466  9.158539  3.890351  9.597126  3.9654372 6.0488634 2.6400673
 7.957049  9.413637  1.4185406 9.352521  5.976438  8.707104  5.7203813
 7.4368305 4.3511043 8.865885  5.781654  2.7391422 6.311746 ]


In [ ]:
ndata = ['all']
ndata = ['all_except',['a_table','m','tec','gamma','cost','zeros','ones', 'total_weight', "disposable_wealth"]]
ndata = [['all_except',['a_table','m','tec','gamma','cost','zeros','ones', 'total_weight', "disposable_wealth"]], ["initial_only",['alpha',"lambda","sigma","sensitivity"]]]
ndata = [['degree','i_a','income','net_trade', 'tech_index','theta', 'wealth', 'wealth_consumption','weighted_degree'], ["initial_only",['alpha',"lambda","sigma","sensitivity"]]]

timestep = 10

if ndata == ['all']:
    ndata = list(attributes.keys())
elif ndata[0] == 'all_except':
    ndata = list(attributes.keys() - ndata[1])
elif sum(1 for item in ndata if isinstance(item, list)) > 1:
    ndata_list = ndata
    initial_only=[]
    for specification in ndata_list:
        if specification == ['all']:
            raise ValueError('Use of "all" is not compatible with multiple data collection specification lists.')
        elif specification[0] == 'all_except':
            ndata = list(attributes.keys() - specification[1])
        elif specification[0] == 'initial_only':
            if timestep == 0:
                initial_only = specification[1]
        else:
            ndata = specification
    ndata=ndata+initial_only


print(ndata)


['degree', 'i_a', 'income', 'net_trade', 'tech_index', 'theta', 'wealth', 'wealth_consumption', 'weighted_degree']
